services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ivf-backend
    ports:
      - "8001:443"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/certificates:/app/certificates:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8001
        NEXT_PUBLIC_WEBSOCKET_URL: ws://localhost:8001
    container_name: ivf-frontend
    ports:
      - "3000:443"
    depends_on:
      - backend
